# Generated by Django 4.0.1 on 2022-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('nickname', models.CharField(default='anonymous', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('about', models.TextField(default='DataFlair Django tutorials')),
            ],
        ),
    ]
